Repository mysteriumnetwork/node, pull requests merged in 2018-09, with the labels that each got.

#326 Fixed some misspells. #308
  cmd/commands/cli/command.go
  openvpn/discovery/dto/payment_method_per_bytes.go
  openvpn/management/connection_mock.go
  openvpn/state.go
  tequilapi/http_api_server.go
  utils/cancelable.go
Labels: documentation

#328 Fixed of building docker images for Ubuntu
  bin/client_docker/ubuntu/Dockerfile
  bin/docker/ubuntu/Dockerfile
  bin/server_docker/ubuntu/Dockerfile
Labels: bug

#378 Custom cancelable implementation replaced with context
  core/connection/interface.go
  core/connection/manager.go
  discovery/discovery.go
  discovery/discovery_fake.go
  discovery/discovery_test.go
  discovery/factory.go
  requests/request.go
  utils/cancelable.go
  utils/cancelable_test.go
Labels: enhancement

#380 Decouple session storage
  bin/check_golint
  core/service/factory.go
  core/service/manager.go
  services/openvpn/session/client_map.go
  services/openvpn/session/manager_auth_middleware_test.go
  services/openvpn/session/validator.go
  services/openvpn/session/validator_mocks.go
  services/openvpn/session/validator_test.go
  session/create_consumer.go
  session/create_consumer_test.go
  session/dialog_handler.go
  session/generator.go
  session/generator_fake.go
  session/generator_test.go
  session/interface.go
  session/manager.go
  session/manager_fake.go
  session/manager_test.go
  session/storage_memory.go
  session/storage_memory_test.go
Labels: enhancement

#393 Updated Readme.md to fit latest release and iptables rule fix backport
  .travis.yml
  INSTALL.md
  README.md
  cmd/commands/license/command.go
  cmd/commands/service/command.go
  cmd/mysterium_node/mysterium_node.go
  e2e/docker-compose.yml
  nat/service_iptables.go
  nat/service_pfctl.go
Labels: bug, documentation

#410 Smaller final binaries
  bin/build
  bin/build_xgo
Labels: enhancement
