Repository mysteriumnetwork/node, pull requests merged in 2019-03, with the labels that each got.

#747 Added service to CLI subcommand
  cmd/commands/cli/command.go
  tequilapi/client/client.go
Labels: enhancement

#755 Hide tequilapi from unknown parties by customising CORS
  cmd/di.go
  tequilapi/api_test.go
  tequilapi/http_api_server.go
  tequilapi/http_api_server_test.go
  tequilapi/http_middlewares.go
  tequilapi/http_middlewares_test.go
  tequilapi/whitelisting_cors_policy.go
  tequilapi/whitelisting_cors_policy_test.go
Labels: security, tequilapi

#760 IP forwarding for Windows with ICS
  nat/factory_windows.go
  nat/service_fake.go
  nat/service_ics.go
  nat/service_ics_test.go
Labels: enhancement, windows

#780 Fixed panic on stopping OpenVPN service with nil port mapping.
  services/openvpn/service/manager.go
  services/openvpn/service/manager_test.go
Labels: bug

#787 Temporary solution for wireguard resources rotation.
  services/wireguard/resources/allocator.go
  services/wireguard/service/service.go
Labels: enhancement

#802 Windows ICS now supports single internal interface
  nat/service_ics.go
  nat/service_ics_test.go
Labels: enhancement

#804 Wireguard provider for Windows uses a single interface
  .gitignore
  Gopkg.lock
  Gopkg.toml
  services/wireguard/connection/connection.go
  services/wireguard/endpoint/endpoint.go
  services/wireguard/endpoint/endpoint_unix.go
  services/wireguard/endpoint/endpoint_windows.go
  services/wireguard/endpoint/kernelspace/client.go
  services/wireguard/endpoint/userspace/client.go
  services/wireguard/endpoint/userspace/tun_windows.go
  services/wireguard/resources/allocator_unix.go
  services/wireguard/resources/allocator_windows.go
  services/wireguard/service/service.go
  services/wireguard/service/service_test.go
  services/wireguard/service/service_unix.go
  services/wireguard/service/service_windows.go
  services/wireguard/wireguard.go
  tequilapi/whitelisting_cors_policy.go
Labels: enhancement

#806 Reassign interface address for Windows ICS
  nat/factory_windows.go
  nat/service_ics.go
  nat/service_ics_test.go
  nat/service_ics_windows.go
Labels: bug

#824 Fixed overwriting pfctl IP forwarding rules
  nat/service_pfctl.go
Labels: bug
