Repository mysteriumnetwork/node, pull requests merged in 2019-05, with the labels that each got.

#924 Build Raspberry Pi image
  .travis.yml
  bin/package/raspberry/config
  bin/package/raspberry/stagemyst/00-install-deb/00-run.sh
  bin/package/raspberry/stagemyst/EXPORT_IMAGE
  bin/package/raspberry/stagemyst/prerun.sh
  bin/package_raspberry
Labels: arm

#922 Use the unified way to print error logs
  cmd/mysterium_node/mysterium_node.go
  utils/stopper.go
Labels: bug

#994 Set required capabilities for myst in deb package
  bin/package/installation/post-install.sh
Labels: bug

#920 Critical NAT hole punchning fixes
  mobile/mysterium/openvpn_connection_setup.go
  nat/traversal/pinger.go
  services/openvpn/client.go
  services/openvpn/client_config.go
  services/openvpn/service/manager.go
Labels: OpenVPN, bug:verified, component:node

#1019 Clean up NAT forwarding rule on OpenVPN service stop
  services/openvpn/service/manager.go
Labels: bug

#1030 Check OpenVPN binary only for OpenVPN service
  cmd/di.go
  cmd/service_bootstrap_desktop.go
Labels: bug

#1036 Fix default mysterium-node config for Raspberry Pi
  bin/package/raspberry/stagemyst/00-install-deb/00-run.sh
  bin/package_raspberry
Labels: arm, bug

#1038 Trigger desktop app build and raspberry image build only for tags
  .travis.yml
Labels: bug, enhancement

#1039 Fix Travis condition
  .travis.yml
Labels: bug

#1069 Refactor pinger without timeouts
  nat/traversal/pinger.go
Labels: work in progress

#1074 Replace wireguardctrl by the migrated project
  Gopkg.lock
  Gopkg.toml
  services/wireguard/endpoint/kernelspace/client.go
Labels: Wireguard

#1081 Autoupdates for myst on raspberry
  bin/package/raspberry/stagemyst/00-install-deb/00-run.sh
  bin/package/raspberry/stagemyst/00-install-deb/files/default-myst-conf
  bin/package/raspberry/stagemyst/00-install-deb/files/unattended-upgrades
Labels: arm, enhancement, epic:raspberry-node

#1073 Built DEB source package and upload to PPA
  .travis.yml
  bin/package/ppa/ppa_key.enc
  bin/release_ppa
  debian/compat
  debian/control
  debian/copyright
  debian/myst.install
  debian/postinst
  debian/postrm
  debian/preinst
  debian/rules
  debian/source/format
  debian/templates
Labels: enhancement

#1087 Fix Travis condition for 0.0.0-dev version of PPA
  .travis.yml
Labels: bug

#1088 Fix panic on session payments second stop
  session/payment/session_payments.go
  session/payment/session_payments_test.go
Labels: bug

#1094 Publish dev version to the node-dev PPA with correct builtin version
  bin/release_ppa
  debian/rules
Labels: bug

#1078 Tequilapi /identities/current endpoint
  cmd/commands/service/command.go
  cmd/di.go
  identity/selector/handler.go
  identity/selector/handler_fake.go
  identity/selector/handler_interface.go
  identity/selector/handler_test.go
  identity/selector/loading.go
  identity/selector/loading_test.go
  tequilapi/client/client.go
  tequilapi/endpoints/identities.go
  tequilapi/endpoints/identities_test.go
Labels: enhancement, tequilapi

#1099 Close NATS connection correctly.
  communication/nats/dialog/dialog.go
  communication/nats/dialog/dialog_establisher.go
  core/connection/manager.go
Labels: bug
