Repository mysteriumnetwork/node, pull requests merged in 2020-02, with the labels that each got.

#1617 Add PPA package for Ubuntu Eoan 19.10
  ci/release/debian.go
  ci/test/testinstall/Dockerfile.ubuntu-eoan
  ci/test/testinstall/install_integration_test.go
  install.sh
Labels: enhancement

#1629 Fix npm repo tagging
  ci/release/github.go
Labels: bug

#1635 Parse flags before applying it to policy fetcher
  cmd/commands/service/command.go
Labels: bug

#1633 Fix session stats on 32bit OS
  core/state/event/event.go
  go.mod
  go.sum
  mobile/mysterium/openvpn3/openvpn3_mock.go
  mobile/mysterium/openvpn_connection_setup.go
  services/openvpn/middlewares/client/bytescount/stats_saver.go
  services/openvpn/service/factory.go
  session/dto.go
  session/event/event.go
  session/event_based_storage.go
  session/storage_memory.go
Labels: bug

#1639 Make whitelisting work again
  core/policy/identity_validator.go
  core/policy/repository.go
  core/policy/repository_test.go
  core/service/manager.go
Labels: bug

#1651 Enable wireguard by default
  bin/package/installation/default
  bin/package/raspberry/files/default-myst-conf
Labels: enhancement

#1655 Do not start NAT pinger if static port specified.
  cmd/di_desktop.go
  docker-compose.e2e-traversal.yml
Labels: enhancement

#1672 Fix panic on the DNS request
  dns/proxy.go
Labels: bug

#1671 Send metrics in a batch request
  cmd/di.go
  config/flags_network.go
  core/node/options.go
  core/node/options_network.go
  core/quality/morqa_transport_test.go
  core/quality/mysterium_morqa.go
  docker-compose.e2e-basic.yml
  docker-compose.e2e-compatibility.yml
  docker-compose.e2e-traversal.yml
  go.mod
  go.sum
  localnet/consumer.sh
  localnet/provider.sh
  logconfig/httptrace/retryablehttp_hooks.go
  metadata/network.go
Labels: enhancement

#1748 Batch mode for CLI
  cmd/commands/cli/command.go
Labels: enhancement

#1727 TTL based NAT hole punching with parallel pings
  cmd/di.go
  config/flags_network.go
  core/port/pool.go
  core/port/pool_fixed.go
  core/port/pool_test.go
  core/service/stub_service.go
  mobile/mysterium/openvpn_connection_setup.go
  mobile/mysterium/wireguard_connection_setup.go
  nat/traversal/nat_proxy.go
  nat/traversal/noop.go
  nat/traversal/pinger.go
  nat/traversal/pinger_test.go
  services/noop/service.go
  services/openvpn/client.go
  services/openvpn/client_config.go
  services/openvpn/client_test.go
  services/openvpn/config_validator.go
  services/openvpn/config_validator_test.go
  services/openvpn/openvpn.go
  services/openvpn/service/manager.go
  services/wireguard/connection/connection.go
  services/wireguard/service/service_unix.go
  services/wireguard/service/service_windows.go
  services/wireguard/wireguard.go
  services/wireguard/wireguard_test.go
  session/create_consumer.go
  session/create_consumer_test.go
  session/manager.go
  session/manager_test.go
Labels: enhancement

#1761 Fix ipset tool for RPi
  bin/package/sudoers/mysterium-node
  debian/control
  firewall/ipset/ipset.go
Labels: bug

#1757 Do not use XGO to build ARM64 target
  ci/packages/package.go
Labels: component:node

#1764 Add flag to enable pprof http endpoints
  cmd/di.go
  config/flags_node.go
  tequilapi/endpoints/pprof.go
Labels: enhancement

#1769 Allow remote IP in firewall before NAT hole punching
  docker-compose.e2e-traversal.yml
  services/openvpn/client.go
  services/openvpn/client_test.go
Labels: bug

#1788 Fix new TTL based NAT hole punching for mobile
  mobile/mysterium/openvpn_connection_setup.go
  mobile/mysterium/wireguard_connection_setup.go
  services/openvpn/client_config.go
  services/openvpn/config_validator.go
  services/openvpn/config_validator_test.go
Labels: bug

#1794 Unsubscribe from broker on service stop
  communication/nats/dialog/dialog_waiter.go
  communication/nats/dialog/dialog_waiter_test.go
Labels: bug
