Repository mysteriumnetwork/node, pull requests merged in 2020-01, with the labels that each got.

#1474 Reuse requests Client to close idle connections by timeout
  tequilapi/client/http_client.go
Labels: enhancement

#1486 Remove old registration process to avoid confusing
  cmd/commands/cli/command.go
Labels: enhancement

#1485 Invoice tracker will now work independent of the order of exchange me…
  session/pingpong/invoice_tracker.go
  session/pingpong/invoice_tracker_test.go
Labels: Payments, bug

#1489 Fix leaking goroutines in the connection manager
  bin/localnet/docker-compose.yml
  core/connection/manager.go
  core/connection/manager_test.go
Labels: bug

#1527 Install wireguard from launchpad instead of deb unstable
  bin/package/raspberry/files/1-setup-node.sh
  install.sh
Labels: priority

#1522 WireGuard NAT hole punching
  .gitlab-ci.yml
  ci/test/e2e.go
  ci/test/test.go
  cmd/di.go
  cmd/di_desktop.go
  core/node/node.go
  core/service/manager.go
  core/service/stub_service.go
  docker-compose.e2e-traversal.yml
  mobile/mysterium/entrypoint.go
  mobile/mysterium/openvpn3/openvpn3_mock.go
  mobile/mysterium/openvpn_connection_setup.go
  mobile/mysterium/wireguard_connection_setup.go
  nat/traversal/config/parser.go
  nat/traversal/nat_proxy.go
  nat/traversal/noop.go
  nat/traversal/pinger.go
  services/noop/service.go
  services/noop/service_test.go
  services/openvpn/client.go
  services/openvpn/openvpn.go
  services/openvpn/service/factory.go
  services/openvpn/service/manager.go
  services/openvpn/service/manager_test.go
  services/wireguard/connection/connection.go
  services/wireguard/connection/connection_factory.go
  services/wireguard/endpoint/create_linux.go
  services/wireguard/endpoint/endpoint.go
  services/wireguard/endpoint/kernelspace/client.go
  services/wireguard/endpoint/userspace/client.go
  services/wireguard/handshake.go
  services/wireguard/service/service_test.go
  services/wireguard/service/service_unix.go
  services/wireguard/wireguard.go
  services/wireguard/wireguard_test.go
  session/create_consumer.go
  session/create_consumer_test.go
  session/create_producer.go
  session/dialog_handler.go
  session/manager.go
Labels: component:node

#1557 Fix getting a single proposal
  core/discovery/apidiscovery/repository.go
Labels: bug

#1578 Bump go-wondershaper to fix bandwidth limiting.
  bin/package/sudoers/mysterium-node
  go.mod
  go.sum
Labels: bug

#1593 Release mysterium-client-npm-package on node release
  ci/release/github.go
Labels: enhancement
