Repository mysteriumnetwork/node, pull requests merged in 2021-07, with the labels that each got.

#3573 Fix mobile connection successful rate
  mobile/mysterium/entrypoint.go
  p2p/channel.go
Labels: bug

#3574 Move docker config to data dir
  bin/docker/docker-entrypoint.sh
Labels: enhancement

#3603 Migrate testnet2 providers automatically
  cmd/di.go
  cmd/di_desktop.go
  core/beneficiary/saver.go
  identity/registry/provider_registrar.go
Labels: component:node

#3607 Do not exit node if broker failed to connect, it will reconnect when automatically.
  communication/nats/connection_wrap.go
  communication/nats/connection_wrap_test.go
  config/flags_node.go
  docker-compose.e2e-basic.yml
  docker-compose.e2e-traversal.yml
  mobile/mysterium/entrypoint.go
Labels: bug

#3627 Do not panic on failed to ping consumer
  p2p/listener.go
Labels: bug

#3636 Disable local service discovery in docker containers
  bin/docker/docker-entrypoint.sh
  config/flags_network.go
  docker-compose.e2e-basic.yml
  docker-compose.e2e-compatibility.yml
  docker-compose.e2e-traversal.yml
  ui/discovery/discovery.go
Labels: enhancement

#3647 Shorten the timeout for hermes requests
  session/pingpong/consumer_balance_tracker.go
Labels: offchain

#3707 Receive pings only from fixed expected peer
  nat/traversal/pinger.go
Labels: bug

#3706 Nat flags cleanup
  cmd/di.go
  cmd/di_desktop.go
  config/flags_network.go
  config/flags_node.go
  config/flags_service_wireguard.go
  core/node/options.go
  core/node/options_network.go
  core/port/pool.go
  core/port/pool_fixed.go
  core/port/pool_test.go
  core/port/range.go
  core/service/session.go
  e2e/mobile_entrypoint_test.go
  mobile/mysterium/entrypoint.go
  nat/traversal/pinger_test.go
  p2p/channel_test.go
  p2p/dialer_test.go
  p2p/listener.go
  services/wireguard/service/options.go
  services/wireguard/service/options_test.go
Labels: enhancement

#3711 win: fix wfp and reenable it
  supervisor/daemon/wireguard/wginterface/firewall/blocker.go
  supervisor/daemon/wireguard/wginterface/firewall/helpers.go
  supervisor/daemon/wireguard/wginterface/firewall/rules.go
  supervisor/daemon/wireguard/wginterface/interface_windows.go
Labels: bug, security

#3702 wg endpoint: Ensure RAII on configure
  services/wireguard/endpoint/endpoint.go
  services/wireguard/endpoint/kernelspace/client.go
  services/wireguard/endpoint/userspace/client.go
  utils/actionstack/actionstack.go
  utils/actionstack/actionstack_test.go
Labels: bug
