Repository mysteriumnetwork/node, pull requests merged in 2021-03, with the labels that each got.

#3157 Set correct MTU size for windows
  supervisor/daemon/wireguard/wginterface/interface_windows.go
Labels: bug

#3209 Block IPv6 traffic for consumer
  core/state/event/event.go
  docker-compose.e2e-basic.yml
  docker-compose.e2e-traversal.yml
  mobile/mysterium/wireguard_connection_setup.go
  utils/netutil/network_darwin.go
  utils/netutil/network_linux.go
  utils/netutil/network_windows.go
Labels: security

#3224 Coingate payment requests now also include a channel address
  cmd/di.go
  pilvytis/api.go
Labels: payments
