Repository mysteriumnetwork/node, pull requests merged in 2021-09, with the labels that each got.

#3927 Support payment gateways
  cmd/commands/account/command.go
  cmd/commands/account/util.go
  cmd/commands/cli/command.go
  cmd/commands/cli/command_orders.go
  metadata/network.go
  mobile/mysterium/coingate.go
  mobile/mysterium/payment_orders.go
  pilvytis/api.go
  pilvytis/order_issuer.go
  pilvytis/order_status_tracker.go
  session/pingpong/consumer_balance_tracker.go
  tequilapi/client/client.go
  tequilapi/contract/pilvytis.go
  tequilapi/docs/swagger.json
  tequilapi/endpoints/assets/docs.go
  tequilapi/endpoints/pilvytis.go
  tequilapi/endpoints/pilvytis_test.go
Labels: payments

#3952 Return if no stage is found
  trace/trace.go
Labels: bug

#3991 nat traversal: concurrency fixes
  nat/traversal/pinger.go
  nat/traversal/pinger_test.go
Labels: bug

#3985 Restrict Host header values for TequilAPI
  config/flags_node.go
  docker-compose.e2e-basic.yml
  docker-compose.e2e-traversal.yml
  tequilapi/http_api_server.go
  tequilapi/middlewares/http_middlewares.go
  utils/domain/whitelist.go
  utils/domain/whitelist_test.go
Labels: security

#3990 Port Pool imrovements
  core/ip/fallbacks.go
  core/port/pool.go
  core/port/pool_test.go
  session/pingpong/hermes_promise_settler.go
  session/pingpong/invoice_tracker.go
  tequilapi/endpoints/sessions_test.go
  utils/random/concurrent.go
  utils/random/concurrent_test.go
  utils/random/timeseeded.go
Labels: bug

#3989 no CORS
  tequilapi/http_api_server.go
Labels: security

#3993 P2P mutual auth
  core/connection/manager.go
  core/service/session_manager.go
  core/service/subscription.go
  identity/integration_test.go
  identity/verifier.go
  identity/verifier_fake.go
  identity/verifier_test.go
  p2p/channel.go
  p2p/common.go
  p2p/context.go
  p2p/dialer.go
  p2p/listener.go
  session/pingpong/factory.go
Labels: security

#4011 Fix panic in MMN launcher info parse
  mmn/mmn.go
Labels: bug
