Repository mysteriumnetwork/node, pull requests merged in 2022-06, with the labels that each got.

#5226 Hermes migration: add blockchain check for open channel
  cmd/di.go
  consumer/migration/hermes_migrator.go
  consumer/migration/migrator_storage.go
  identity/registry/transactor.go
  tequilapi/endpoints/identities_test.go
Labels: payments

#5238 Fix timer
  session/pingpong/factory.go
  session/pingpong/invoice_tracker.go
Labels: bug

#5245 Add bandwidth min filter for proposals
  core/discovery/proposal/filter.go
  market/mysterium/dto.go
Labels: enhancement
